version: "3.8"
services:
  book-sen-front:
    build:
      context: ./front-end
    restart: always
    container_name: book-sen-front
    ports:
      - "5173:5173"


  book-sen-api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    container_name: book-sen-api
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_NAME: book-sen-api
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATA_MONGODB_USERNAME: root
      SPRING_DATA_MONGODB_PASSWORD: password
      SPRING_DATA_MONGODB_DATABASE: book-sen-db
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_HOST: mongodb

    networks:
      - backend


networks:
  backend:
    driver: bridge
